% Classic ERP analysis of Tamari and Yvonne's data

% Multiple comparisions correction
% 'none' - No correction
% 'bonferroni' - Bonferroni correction
% 'holm' - Holm-Bonferroni step-down
% 'fdr_bh' - Benjamini-Hochberg FDR
% 'fdr_by' - Benjamini-Yekutieli FDR
% 'sidak' - Šidák correction
correction = 'holm';

fprintf("Tamari's data:\n\n");
fprintf("Subsequent Memory Effect");
tamari_sme_results = erp_ttest_batch('tamari_SMEhits_ERP', 'tamari_SMEmisses_ERP', ...          % conditions
                                    [21, 36, 87, 101, 153, 224], ...                            % electrodes
                                    [400 700; 700 900; 900 1200; 1500 2000; 2000 2500], ...     % time windows
                                    500, ...                                                    % Hz
                                    0.05, ...                                                   % alpha value
                                    correction);                                                % multiple comparisons correction
fprintf("Old/New Effect");
tamari_oldnew_results = erp_ttest_batch('tamari_INhits_ERP', 'tamari_REcorrej_ERP', ...
                                    [21, 87, 101, 153], ...
                                    [400 600; 600 800], ...
                                    500, ...
                                    0.05, ...
                                    correction);
fprintf("Retrieval Success Effect");
tamari_rse_results = erp_ttest_batch('tamari_INhits_ERP', 'tamari_INmisses_ERP', ...
                                    [21, 87, 101, 154], ...
                                    [400 600; 600 800], ...
                                    500, ...
                                    0.05, ...
                                    correction);

fprintf("Yvonne's data:\n\n");
fprintf("Subsequent Memory Effect");
yvonne_sme_results = erp_ttest_batch('yvonne_SMEhits_ERP', 'yvonne_SMEmisses_ERP', ...                        
                                    [21, 36, 101, 224], ...                            
                                    [400 700; 700 900; 900 1200; 1500 2000], ... 
                                    250, ...
                                    0.05, ...                                                   
                                    correction);                                                
fprintf("Old/New Effect\n");
fprintf("Yvonne's dataset doesn't have correct rejections. Can't calculate.\n\n");
fprintf("Retrieval Success Effect");
yvonne_rse_results = erp_ttest_batch('yvonne_INhits_ERP', 'yvonne_INmisses_ERP', ...
                                    [21, 87, 101, 153], ...
                                    [400 600; 600 800], ...
                                    250, ...
                                    0.05, ...
                                    correction);